-- Church in Conversation — Supabase schema
-- Run this once in the Supabase SQL editor after the project is created
-- (Table Editor -> SQL Editor -> New query -> paste -> Run).
-- Extends Supabase's built-in auth.users rather than replacing it.

-- 1. profiles: one row per signed-up user, created automatically on signup.
create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  pilot_cohort text,                         -- e.g. 'pilot_1', 'pilot_2'; null until assigned
  max_sessions integer not null default 5,
  role_hint text,                            -- 'regular_visitor' | 'pastor_teacher' | 'academic_scholar' | 'reevaluation'
  created_at timestamptz not null default now()
);

-- Auto-create a profile row whenever a new auth user is created.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (user_id) values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. pilot_requests: the "express interest" form submissions from cic-website/pilot.html.
create table public.pilot_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  seat text,                                 -- which of the 4 seats they applied for
  why_interested text,
  referred_by text,
  status text not null default 'pending',    -- 'pending' | 'approved' | 'declined'
  submitted_at timestamptz not null default now()
);

-- 2b. pilot_feedback: post-conversation feedback from cic-website/pilot-feedback.html.
-- A different thing from pilot_requests above (that's "I'd like to join";
-- this is "here's what the conversation I already had was actually like")
-- - added 2026-08-05 rather than reusing pilot_requests' mismatched schema,
-- which the full-system review's own suggested fix would have done
-- (Readiness P1-9b), caught by checking the endpoint's actual Pydantic
-- model before wiring the form to it.
create table public.pilot_feedback (
  id uuid primary key default gen_random_uuid(),
  perspective text,                          -- which of the four perspectives they engaged as
  tradition text,                            -- free text, which Representative(s)/world(s)
  confusing text,
  invented_or_overstated text,
  what_it_opened text,
  fundable_potential text,
  anything_else text,
  name text,                                 -- optional, blank = anonymous
  email text,                                -- optional, only if open to follow-up
  submitted_at timestamptz not null default now()
);

-- 3. sessions: one row per conversation session (replaces the in-memory dict).
create table public.sessions (
  id uuid primary key,                       -- same UUID already generated by the backend
  user_id uuid references auth.users(id) on delete set null,
  world_ids text[] not null,
  phase text,
  turn_count integer not null default 0,
  status text not null default 'active',     -- 'active' | 'closed'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. messages: append-only transcript (replaces the overwrite-JSON transcript files).
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  role text not null,                        -- 'user' | 'assistant' | 'facilitator'
  name text,
  content text not null,
  citations jsonb,
  created_at timestamptz not null default now()
);

-- 5. api_usage: per-model-call token/cost ledger — the real per-user credit meter.
create table public.api_usage (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.sessions(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost numeric(10, 6) not null default 0,
  created_at timestamptz not null default now()
);

-- 5b. session_events: the append-only conversation event log (S4.2,
-- Pass 1 §6.7) — every spoken event, classifier decision, and state
-- transition, in order. The backend's in-process projection is derived
-- from exactly these rows' shape; this table is what makes the audit
-- endpoint durable beyond a process restart. No foreign key to
-- public.sessions on purpose: events for a session are appended before
-- transcript_logging upserts the session row, and the log must never
-- fail because a companion row doesn't exist yet.
create table public.session_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  seq integer not null,
  type text not null,
  payload jsonb,
  ts timestamptz not null default now(),
  unique (session_id, seq)
);

-- Helpful indexes for the queries Mark will run to review activity per participant.
create index idx_sessions_user_id on public.sessions(user_id);
create index idx_messages_session_id on public.messages(session_id);
create index idx_api_usage_user_id on public.api_usage(user_id);
create index idx_session_events_session_id on public.session_events(session_id);

-- Row-level security: enabled on everything by default. The backend talks to
-- Postgres using the service-role key (which bypasses RLS entirely), so no
-- policies are strictly required for the app to function - but RLS is left
-- ON so that no other key (e.g. the public anon key, if ever exposed to the
-- browser) can read or write these tables without an explicit policy.
alter table public.profiles enable row level security;
alter table public.pilot_requests enable row level security;
alter table public.sessions enable row level security;
alter table public.messages enable row level security;
alter table public.api_usage enable row level security;
alter table public.session_events enable row level security;

-- Allow the pilot.html interest form to insert (not read) pilot_requests using
-- the public anon key, if you choose to submit directly from the browser
-- instead of through the backend's /api/pilot/request endpoint.
create policy "anyone can submit a pilot request"
  on public.pilot_requests for insert
  to anon
  with check (true);

-- 6. referral_invites: one-hop-only referral codes. A tester who completes
-- their post-conversation survey may generate exactly one of these; the
-- friend who redeems it gets their own access but cannot generate a further
-- referral (enforced in the backend by checking profiles.referred_by_invite_id
-- before allowing a new invite to be generated - see /api/referral/generate).
create table public.referral_invites (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,                 -- short, shareable (e.g. 'CIC-7F3K')
  referring_user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_by_user_id uuid references auth.users(id) on delete set null,
  redeemed_email text,                       -- set on redemption, before the invited user's account exists
  status text not null default 'active',     -- 'active' | 'redeemed' | 'revoked'
  created_at timestamptz not null default now(),
  redeemed_at timestamptz
);

alter table public.profiles
  add column referred_by_invite_id uuid references public.referral_invites(id);

create index idx_referral_invites_referring_user on public.referral_invites(referring_user_id);
alter table public.referral_invites enable row level security;
