"""Thin CLI over the pure confinement battery, same shape as
engine/m2/cli.py and engine/m1/selftest.py's own entry points. `check`
(the CI-blocking command, Q3) lands in increment 4 - this increment's CI
job runs `pytest` and `selftest` only, in report mode (D3 SS7, increment
3's own row).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from engine.m1.loader import load_world_records
from engine.m1.registry import load_registry

from .confinement import run_all
from .loader import load_shelf
from .shelf import Shelf

REPO_ROOT = Path(__file__).resolve().parents[2]
_EDITION_PATH = re.compile(r"cic/texts/([\w\-]+\.(?:txt|xml))")


def _shelf_for(world_key: str) -> tuple[Shelf, dict]:
    registry = load_registry()
    entry = registry.get(world_key)
    if entry is None:
        raise SystemExit(f"{world_key!r} is not in the registry")
    census_id = entry.get("census_id")
    if not census_id:
        raise SystemExit(f"{world_key!r} has no census_id - nothing to build a shelf from")
    records = load_world_records(world_key)
    shelf = load_shelf(world_key=world_key, census_id=census_id, records=records)
    return shelf, records


def _off_shelf_reads(records: dict, shelf: Shelf) -> list[dict]:
    """Report-only: every kind: absence record whose named file this world's
    own bucket doesn't claim - the off-shelf reads Q5 licenses at build
    time, named here so they're logged, not hidden (D3 SS1.4's own
    absence-probe row)."""
    reads = []
    for rid, rec in records.items():
        if rec.get("record_type") != "source" or rec.get("kind") != "absence":
            continue
        m = _EDITION_PATH.search(str(rec.get("edition") or ""))
        if not m:
            continue
        filename = m.group(1)
        reads.append({"record": rid, "file": filename, "on_shelf": filename in shelf.files})
    return reads


def cmd_report(args: argparse.Namespace) -> int:
    shelf, records = _shelf_for(args.world_key)
    findings = run_all(records, shelf)
    total = sum(len(v) for v in findings.values())
    print(json.dumps({
        "world": args.world_key,
        "census_id": shelf.census_id,
        "clean": total == 0,
        "findings": findings,
        "off_shelf_reads": _off_shelf_reads(records, shelf),
    }, indent=2))
    return 0


def _render_shelf_table(world_key: str, shelf: Shelf) -> str:
    """Same shape tools/gen_shelf.py's own render() produces - increment 9
    points that tool's own SHELF.md output at this instead and retires its
    line-regex bucket reader."""
    by_role: dict[str, int] = {}
    for row in shelf.rows.values():
        by_role[row.get("role") or "?"] = by_role.get(row.get("role") or "?", 0) + 1
    lines = [
        f"# Shelf — `{world_key}`",
        "",
        f"Tradition: `{shelf.census_id}` · {len(shelf.rows)} works · "
        + " · ".join(f"{r}: {n}" for r, n in sorted(by_role.items())),
        "",
        "Generated by `python -m engine.m9.cli shelf`. Do not edit; regenerate. Roles: "
        "`tradition` is this world's own voice and may be voiced; `context`, `antecedent` "
        "and `transmission` may be cited as evidence, and are voiceable only when a "
        "documented-exchange row says so (CM-8).",
        "",
        "| work | author | file | locus | role | confidence | voice_of | documented_exchange |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in sorted(shelf.rows.values(), key=lambda r: (r.get("role") or "", r.get("author") or "", r.get("work") or "")):
        lines.append(
            f"| {row.get('work', '')} | `{row.get('author', '')}` | `{row.get('source_file', '')}` | "
            f"{row.get('locus', '')} | {row.get('role', '')} | {row.get('confidence', '')} | "
            f"{row.get('voice_of') or ''} | {row.get('documented_exchange') or ''} |"
        )
    return "\n".join(lines) + "\n"


def cmd_shelf(args: argparse.Namespace) -> int:
    shelf, _records = _shelf_for(args.world_key)
    text = _render_shelf_table(args.world_key, shelf)
    if args.stdout:
        print(text)
        return 0
    target_dir = REPO_ROOT / "worlds" / args.world_key
    if not target_dir.is_dir():
        print(f"{args.world_key}: no {target_dir.relative_to(REPO_ROOT)}/ yet - printing instead", file=sys.stderr)
        print(text)
        return 0
    (target_dir / "SHELF.md").write_text(text, encoding="utf-8")
    print(f"{args.world_key}: {target_dir.relative_to(REPO_ROOT)}/SHELF.md — {len(shelf.rows)} works")
    return 0


def cmd_selftest(args: argparse.Namespace) -> int:
    from . import selftest

    return selftest.main()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m engine.m9.cli")
    sub = parser.add_subparsers(dest="command", required=True)

    report = sub.add_parser("report", help="build one world's shelf, run the confinement battery, print findings")
    report.add_argument("world_key")
    report.set_defaults(func=cmd_report)

    shelf = sub.add_parser("shelf", help="render one world's SHELF.md table from its real, computed shelf")
    shelf.add_argument("world_key")
    shelf.add_argument("--stdout", action="store_true", help="print instead of writing worlds/<code>/SHELF.md")
    shelf.set_defaults(func=cmd_shelf)

    selftest_p = sub.add_parser("selftest", help="M1-selftest-shaped proof: the clean fixture is clean, every seeded M9 defect fires its named check")
    selftest_p.set_defaults(func=cmd_selftest)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
