"""Prompts for facilitator and representative agents."""

from app.prompts.facilitator_prompts import (
    FACILITATOR_ACUTE_DISTRESS_A1_PROMPT,
    FACILITATOR_ACUTE_DISTRESS_A2_PROMPT,
    FACILITATOR_ACUTE_DISTRESS_CONTINUATION_PROMPT,
    FACILITATOR_BRIDGE_PROMPT,
    FACILITATOR_CLOSING_PROMPT,
    FACILITATOR_FRAME_BREAKER_CLASSIFIER_PROMPT,
    FACILITATOR_FRAME_BREAKER_RESPONSE_PROMPT,
    FACILITATOR_HANDOFF_PROMPT,
    FACILITATOR_HARMFUL_DYNAMIC_CONTINUATION_PROMPT,
    FACILITATOR_HARMFUL_DYNAMIC_PROMPT,
    FACILITATOR_MONITORING_PROMPT,
    FACILITATOR_RECEPTION_PROMPT,
    FACILITATOR_RELATIONAL_SAFETY_CLASSIFIER_PROMPT,
    FACILITATOR_REROOT_PROMPT,
)
from app.prompts.representative_prompts import build_representative_prompt

__all__ = [
    "FACILITATOR_RECEPTION_PROMPT",
    "FACILITATOR_HANDOFF_PROMPT",
    "FACILITATOR_MONITORING_PROMPT",
    "FACILITATOR_REROOT_PROMPT",
    "FACILITATOR_CLOSING_PROMPT",
    "FACILITATOR_BRIDGE_PROMPT",
    "FACILITATOR_FRAME_BREAKER_CLASSIFIER_PROMPT",
    "FACILITATOR_FRAME_BREAKER_RESPONSE_PROMPT",
    "FACILITATOR_RELATIONAL_SAFETY_CLASSIFIER_PROMPT",
    "FACILITATOR_ACUTE_DISTRESS_A1_PROMPT",
    "FACILITATOR_ACUTE_DISTRESS_A2_PROMPT",
    "FACILITATOR_ACUTE_DISTRESS_CONTINUATION_PROMPT",
    "FACILITATOR_HARMFUL_DYNAMIC_PROMPT",
    "FACILITATOR_HARMFUL_DYNAMIC_CONTINUATION_PROMPT",
    "build_representative_prompt",
]
