export const deeperCopy = {
  haveCode: 'I have a code',
  getCode: 'Get a code',
  getMore: 'Get more',
  low: 'Your code is running low.',
  fieldLabel: 'Your code',
  useCode: 'Use this code',
  saved: 'Code saved on this device.',
  removeCode: 'Remove code',
  badCode: "That doesn't look like a code. Check it and try again.",
  claimAsk: 'A code came with this link. Use it?',
  claimReplace: 'You already have a code. This one will be added to it.',
  claimUse: 'Use it',
  claimLater: 'Not now',
  claimFailed: "We couldn't get that code. Try the page where you paid.",
  balance: (n: number) => (n === 1 ? '1 exchange left on your code.' : `${n} exchanges left on your code.`),
};
