#!/usr/bin/env python3
"""Regenerate world-build-docs/pahc/VOICE-INDEX.md from
records/pahc/voice_craft/*.md and records/pahc/demonstration/*.md.

Usage: python3 world-build-docs/pahc/generate_voice_index.py
"""
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from engine.m1.loader import load_world_records


REQUIRED_SET = {
    "Center cells (C-I, C-E, C-P, C-T)": ["C-I", "C-E", "C-P", "C-T"],
    "Identity-collision (F6-P x2, F6-T x1)": ["F6-P", "F6-P", "F6-T"],
}


def main():
    recs = load_world_records("pahc")
    craft = {k: v for k, v in recs.items() if v["record_type"] == "voice_craft"}
    demos = {k: v for k, v in recs.items() if v["record_type"] == "demonstration"}

    lines = [
        "# pahc Voice Index",
        "",
        "**GENERATED from records/pahc/voice_craft/ and records/pahc/demonstration/ — "
        "do not hand-edit.** Regenerate with "
        "`python3 world-build-docs/pahc/generate_voice_index.py` after any change. "
        "Companion to the Representative voice build step "
        "(Redesign-Spec/CiC-Program-Spec.md SS4.3 step 5).",
        "",
        f"**Totals:** {len(craft)} voice_craft, {len(demos)} demonstration.",
        "",
        "## Required-set check", "",
    ]

    cells_covered = sorted({c for r in demos.values() for c in (r.get("canon_cells") or [])})
    center_covered = sorted({c for r in demos.values()
                              if any(c.startswith("C-") for c in (r.get("canon_cells") or []))
                              for c in (r.get("canon_cells") or []) if c.startswith("C-")})
    identity_collision = sorted(k for k, r in demos.items() if "identity-collision" in (r.get("tags") or []))
    honest_limit_voice = sorted(k for k in demos if "honest-limit" in k or "limit" in k)
    lament = sorted(k for k in demos if "lament" in k)

    lines.append(f"- **Center cells covered:** {', '.join(center_covered) or 'NONE'} "
                 f"(spec requires center cells first)")
    lines.append(f"- **Identity-collision demonstrations:** {len(identity_collision)} "
                 f"({', '.join(identity_collision)}) - spec requires these before any world opens")
    lines.append(f"- **Honest-limit-in-voice demonstration(s):** {', '.join(honest_limit_voice) or 'NONE'}")
    lines.append(f"- **Lament exchange(s):** {', '.join(lament) or 'NONE'}")
    lines.append("")

    lines += ["## voice_craft", ""]
    for cid in sorted(craft):
        r = craft[cid]
        lines.append(f"### {cid}")
        lines.append(f"- **identity:** {r['identity']}")
        lines.append("- **flavor_notes:**")
        for n in r.get("flavor_notes") or []:
            lines.append(f"  - [{n.get('segment')}/{n.get('tag')}] {n.get('note')}")
        lines.append("- **characteristic_concerns:**")
        for c in r.get("characteristic_concerns") or []:
            lines.append(f"  - {c}")
        lines.append(f"- **guard:** {r['guard']}")
        lines.append("")

    lines += ["## Demonstrations", ""]
    for did in sorted(demos):
        r = demos[did]
        cc = ", ".join(r.get("canon_cells") or []) or "-"
        tags = ", ".join(r.get("tags") or []) or "-"
        lines.append(f"### {did}")
        lines.append(f"- **canon_question_id:** {r.get('canon_question_id')}")
        lines.append(f"- **canon_cells:** {cc}")
        lines.append(f"- **tags:** {tags}")
        for turn in r.get("exchange") or []:
            lines.append(f"  - **{turn['speaker']}:** {turn['text']}")
        lines.append("")

    lines += ["", "---", "<!-- generated by generate_voice_index.py -->", ""]

    out = pathlib.Path(__file__).resolve().parent / "VOICE-INDEX.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} | voice_craft: {len(craft)} | demonstration: {len(demos)} "
          f"| identity-collision: {len(identity_collision)}")


if __name__ == "__main__":
    main()
