#!/usr/bin/env python3
"""Regenerate world-build-docs/pahc/ANSWER-CANON-INDEX.md from
records/pahc/doctrinal_witness/*.md and records/pahc/quote/*.md.

Usage: python3 world-build-docs/pahc/generate_answer_canon_index.py
"""
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from engine.m1.loader import load_world_records, load_fleet_records
from engine.m1 import canon


def main():
    recs = load_world_records("pahc")
    fleet = load_fleet_records()
    witnesses = {k: v for k, v in recs.items() if v["record_type"] == "doctrinal_witness"}
    quotes = {k: v for k, v in recs.items() if v["record_type"] == "quote"}

    lines = [
        "# pahc Answer Canon Index",
        "",
        "**GENERATED from records/pahc/doctrinal_witness/ and records/pahc/quote/ — "
        "do not hand-edit.** Regenerate with "
        "`python3 world-build-docs/pahc/generate_answer_canon_index.py` after any change.",
        "",
        f"**Totals:** {len(witnesses)} doctrinal_witness, {len(quotes)} quote.",
        "",
        "## Canon-coverage snapshot", "",
    ]
    cells = sorted(canon.valid_cells(fleet))
    blank = [c for c in cells if canon.classify_cell(c, recs)["status"] == "empty"]
    lines.append(f"- **{len(cells)} total cells; {len(blank)} still blank.**")
    if blank:
        lines.append(f"- **Still blank:** {', '.join(blank)}")
    else:
        lines.append(
            "- Every fleet canon cell now has at least one substantive record "
            "(doctrinal_witness/term/story/quote) or exactly one honest_limit. "
            "Step 9 (stories) may still add further, non-required coverage."
        )

    lines += ["", "## Doctrinal witnesses", ""]
    for wid in sorted(witnesses):
        r = witnesses[wid]
        cc = ", ".join(r["canon_cells"]) or "-"
        lines.append(f"### {wid}")
        lines.append(f"- **canon_cells:** {cc}")
        lines.append(f"- **formation_confidence:** {r['confidence']['formation_confidence']}")
        lines.append("- **positions:**")
        for item in r.get("positions") or []:
            lines.append(f"  - {item}")
        lines.append("- **tensions:**")
        for item in r.get("tensions") or []:
            lines.append(f"  - {item}")
        lines.append("")

    lines += ["## Quotes", ""]
    for qid in sorted(quotes):
        r = quotes[qid]
        cc = ", ".join(r["canon_cells"]) or "-"
        lines.append(f"### {qid}")
        lines.append(f"- **canon_cells:** {cc}")
        lines.append(f"- **speaker_or_author:** {r['speaker_or_author']}")
        lines.append(f"- **license:** {r['license']}")
        lines.append(f"- **text:** {r['text']}")
        lines.append("")

    lines += ["", "---", "<!-- generated by generate_answer_canon_index.py -->", ""]

    out = pathlib.Path(__file__).resolve().parent / "ANSWER-CANON-INDEX.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} | doctrinal_witness: {len(witnesses)} | quote: {len(quotes)} | blank cells: {len(blank)}")


if __name__ == "__main__":
    main()
