#!/usr/bin/env python3
"""Regenerate world-build-docs/pahc/CONTESTED-CLAIMS-INDEX.md from
records/pahc/contested_claim/*.md and records/pahc/honest_limit/*.md.

Usage: python3 world-build-docs/pahc/generate_contested_index.py
"""
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from engine.m1.loader import load_world_records
from engine.m1 import canon


def main():
    recs = load_world_records("pahc")
    claims = {k: v for k, v in recs.items() if v["record_type"] == "contested_claim"}
    limits = {k: v for k, v in recs.items() if v["record_type"] == "honest_limit"}

    lines = [
        "# pahc Contested Claims & Honest Limits Index",
        "",
        "**GENERATED from records/pahc/contested_claim/ and records/pahc/honest_limit/ — "
        "do not hand-edit.** Regenerate with "
        "`python3 world-build-docs/pahc/generate_contested_index.py` after any change.",
        "",
        f"**Totals:** {len(claims)} contested_claim, {len(limits)} honest_limit.",
        "",
        "## Contested claims", "",
    ]
    for cid in sorted(claims):
        r = claims[cid]
        cc = ", ".join(r["canon_cells"]) or "-"
        lines.append(f"### {cid}")
        lines.append(f"- **canon_cells:** {cc}")
        lines.append(f"- **formation_confidence:** {r['confidence']['formation_confidence']}")
        lines.append(f"- **claim:** {r['claim']}")
        lines.append(f"- **concedes:** {r['concedes']}")
        lines.append("")

    lines += ["## Honest limits", ""]
    for lid in sorted(limits):
        r = limits[lid]
        cc = ", ".join(r["canon_cells"]) or "-"
        lines.append(f"### {lid}")
        lines.append(f"- **canon_cells:** {cc}")
        lines.append(f"- **why_sources_cannot_answer:** {r['why_sources_cannot_answer']}")
        lines.append("")

    lines += ["## Canon-coverage snapshot (informational; the real gate is engine.m1.gates.gate_canon_coverage)", ""]
    fleet = {**{k: v for k, v in load_world_records("_fleet").items()}}
    all_ids = sorted(canon.valid_cells(fleet))
    blank = []
    for cell in all_ids:
        status = canon.classify_cell(cell, recs)["status"]
        if status == "empty":
            blank.append(cell)
    lines.append(f"- **{len(all_ids)} total cells; {len(blank)} still blank** (doctrinal_witness/term/story/quote or honest_limit are the only cell-closing record types - this index's own contested_claim canon_cells do NOT close a cell, per canon.substantive_types()).")
    lines.append(f"- **Still blank:** {', '.join(blank)}")
    lines.append(
        "- These 17 remaining blanks are deferred to Steps 8-9 (doctrinal_witness/quote, story) as this "
        "world's own evidentiary base can answer most of them; F5-E is the only cell this step closed, "
        "via honest_limit, because it is a genuine structural evidentiary gap (no material-culture source "
        "exists in this world's registry), not merely an unbuilt topic."
    )

    lines += ["", "---", "<!-- generated by generate_contested_index.py -->", ""]

    out = pathlib.Path(__file__).resolve().parent / "CONTESTED-CLAIMS-INDEX.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} | contested_claim: {len(claims)} | honest_limit: {len(limits)} | blank cells: {len(blank)}")


if __name__ == "__main__":
    main()
