#!/usr/bin/env python3
"""The Atlas census as a shelf label - every entry an assignment can target.

The census file is 274 entries of participant-facing tile copy: status words,
ground colours, floor reasoning, sourcing notes. An assignment thread needs
four fields from it - id, name, dates, region - plus the status, and reading
the rest is how a parsing job turns into an opinion about which worlds matter.

So this is the census reduced to what places a work, grouped by era. It is
regenerated, never hand-edited, and lives beside the map it feeds.

    python cic/engine/atlas_targets.py           # write cic/corpus-map/ATLAS-TARGETS.md
    python cic/engine/atlas_targets.py --print   # to stdout instead
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CENSUS = REPO_ROOT / "cic-website" / "data" / "world-census.json"
TARGET = REPO_ROOT / "cic" / "corpus-map" / "ATLAS-TARGETS.md"


def render() -> str:
    data = json.loads(CENSUS.read_text(encoding="utf-8"))
    out = [
        "# Atlas census - every assignment target\n",
        "Generated by `cic/engine/atlas_targets.py` from "
        "`cic-website/data/world-census.json`. **Assign to the `id` column** - it is also the "
        "filename of the corpus-map bucket, which is the whole alignment mechanism.\n",
        "All 274 entries are valid targets. That includes the 215 marked *Pre-Survey Candidate* "
        "(Mark, 2026-08-26: material plainly belonging to one of them belongs there rather than "
        "held back - placing a source is not a claim that the era's survey has run), and the "
        "four marked ⛔ *Excluded - Doctrinal Floor*, which will never be built as worlds but "
        "still need a home for the heresiological material the corpus carries about them. A "
        "built world may draw on those only as `register: etic` - described from outside, never "
        "as its own voice.\n",
        "The six *Built & Live* entries are the six worlds that exist today. There is one "
        "taxonomy here, not two.\n",
    ]

    by_era: dict[int, list[dict]] = {}
    for movement in data["movements"]:
        by_era.setdefault(movement["era"], []).append(movement)

    for era_n in sorted(by_era):
        era = next((e for e in data["eras"] if e.get("num") == era_n), {})
        rows = sorted(by_era[era_n], key=lambda m: (m.get("start") or 0, m["id"]))
        out.append(f"\n## Era {era_n} ({era.get('no', '')}) — {era.get('title', '')}, "
                   f"{era.get('dates', '')}  ·  {len(rows)} entries\n")
        if era.get("stepStatus"):
            out.append(f"*{era['stepStatus']}*\n")
        out.append("| id | name | dates | region | status |")
        out.append("|---|---|---|---|---|")
        for m in rows:
            status = m.get("status", "")
            if m.get("beyondFloor"):
                status += " ⛔"
            region = (m.get("region") or "—").replace("|", "\\|")[:52]
            out.append(f"| `{m['id']}` | {m.get('name', '')} | {m.get('dates', '')} | "
                       f"{region} | {status} |")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python cic/engine/atlas_targets.py")
    parser.add_argument("--print", dest="to_stdout", action="store_true")
    text = render()
    if parser.parse_args(argv).to_stdout:
        print(text)
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
