#!/usr/bin/env python3
"""The Atlas census as a shelf label - every entry an assignment can target.

The census file is participant-facing tile copy: status words, ground
colours, floor reasoning, sourcing notes. An assignment thread needs four
fields from it - id, name, dates, region - plus the status, and reading
the rest is how a parsing job turns into an opinion about which worlds
matter. The entry count and Built & Live count are computed fresh from the
census every run (render(), below) rather than stated here, precisely
because this file's own first draft hardcoded "274 entries" and "six
worlds" into prose and both went stale the next time a world went live or
a batch of entries was added - caught 2026-09-02, when the real numbers
had already drifted to 292 and seven without this docstring or render()'s
own output noticing.

So this is the census reduced to what places a work, grouped by era. It is
regenerated, never hand-edited, and lives beside the map it feeds.

    python cic/engine/atlas_targets.py           # write cic/corpus-map/ATLAS-TARGETS.md
    python cic/engine/atlas_targets.py --print   # to stdout instead
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CENSUS = REPO_ROOT / "cic-website" / "data" / "world-census.json"
TARGET = REPO_ROOT / "cic" / "corpus-map" / "ATLAS-TARGETS.md"


def render() -> str:
    data = json.loads(CENSUS.read_text(encoding="utf-8"))
    movements = data["movements"]
    total = len(movements)
    built_live = sum(1 for m in movements if m.get("status") == "Built & Live")
    pre_survey = sum(1 for m in movements if m.get("status") == "Pre-Survey Candidate")
    excluded = sum(1 for m in movements if str(m.get("status", "")).startswith("Excluded - Doctrinal Floor"))
    out = [
        "# Atlas census - every assignment target\n",
        "Generated by `cic/engine/atlas_targets.py` from "
        "`cic-website/data/world-census.json`. **Assign to the `id` column** - it is also the "
        "filename of the corpus-map bucket, which is the whole alignment mechanism.\n",
        f"All {total} entries are valid targets. That includes the {pre_survey} marked "
        "*Pre-Survey Candidate* (Mark, 2026-08-26: material plainly belonging to one of them "
        "belongs there rather than held back - placing a source is not a claim that the era's "
        f"survey has run), and the {excluded} marked ⛔ *Excluded - Doctrinal Floor*, which will "
        "never be built as worlds but still need a home for the heresiological material the "
        "corpus carries about them. A built world may draw on those only as `register: etic` - "
        "described from outside, never as its own voice.\n",
        f"The {built_live} *Built & Live* entries are the {built_live} worlds that exist today. "
        "There is one taxonomy here, not two. (This count, like the total above, is computed "
        "from the census every run - both were hand-typed as fixed numbers in this file's first "
        "draft and had already drifted once, unnoticed, by the time that was caught 2026-09-02.)\n",
    ]

    by_era: dict[int, list[dict]] = {}
    for movement in data["movements"]:
        by_era.setdefault(movement["era"], []).append(movement)

    for era_n in sorted(by_era):
        era = next((e for e in data["eras"] if e.get("num") == era_n), {})
        rows = sorted(by_era[era_n], key=lambda m: (m.get("start") or 0, m["id"]))
        out.append(f"\n## Era {era_n} ({era.get('no', '')}) — {era.get('title', '')}, "
                   f"{era.get('dates', '')}  ·  {len(rows)} entries\n")
        if era.get("stepStatus"):
            out.append(f"*{era['stepStatus']}*\n")
        out.append("| id | name | dates | region | status |")
        out.append("|---|---|---|---|---|")
        for m in rows:
            status = m.get("status", "")
            if m.get("beyondFloor"):
                status += " ⛔"
            region = (m.get("region") or "—").replace("|", "\\|")[:52]
            out.append(f"| `{m['id']}` | {m.get('name', '')} | {m.get('dates', '')} | "
                       f"{region} | {status} |")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python cic/engine/atlas_targets.py")
    parser.add_argument("--print", dest="to_stdout", action="store_true")
    text = render()
    if parser.parse_args(argv).to_stdout:
        print(text)
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
