#!/usr/bin/env python3
"""Merge per-volume assignment staging files into the corpus map.

WHY A STAGING STEP AT ALL. The map is stored one file per Atlas entry, which
is right for reading and for the `census_id -> filename` join. It is exactly
wrong for writing: the assignment work partitions naturally by SOURCE VOLUME
(one worker reads anf02, another npnf204), and any two volumes can contribute
to the same Atlas entry - Athanasius' Vita in npnf204 and Palladius' Lausiac
History both land in `desert-monasticism`. Parallel workers writing bucket
files directly would race on exactly the entries that matter most, and the
loser's work would vanish silently.

So workers write `cic/corpus-map/_staging/<volume>.yaml`, one file each, never
shared. Each entry is ONE WORK with the atlas entries it belongs to:

    source_file: anf02_hermas-tatian-athenagoras-theophilus-clement-alexandria.xml
    assignments:
      - work: "The Stromata"
        author: clement_alex
        locus: "div2 5.4"
        atlas_ids: [alexandria-catechetical]
        role: tradition
        confidence: assigned
        note: >
          ...

This transposes that to the stored shape. The two are the same data: per-work
with many entries, and per-entry with many works, are projections of one
relation. The staging shape is the writer's view; the bucket shape is the
reader's.

NON-EXCLUSIVITY SURVIVES THE MERGE, and that is the point of doing it here
rather than by hand. A work naming three `atlas_ids` is written into three
bucket files, deliberately: an exclusive partition would strip desert of the
Vita Antonii, which is its evidential base. See corpus_map.py's docstring.

    python cic/engine/corpus_map_merge.py --check    # report, write nothing
    python cic/engine/corpus_map_merge.py            # full merge: write every bucket, prune orphans
    python cic/engine/corpus_map_merge.py --write-only anf02   # write only the buckets anf02's
                                                                 # own staging file touches (see
                                                                 # merge()'s own docstring)
    python cic/engine/corpus_map_merge.py --assign-ids         # give every staging row without a
                                                                 # `row_id` one, written into staging

ROW IDS. Every staging row carries a `row_id`, `<file-stem>--<work-slug>`. The
id is assigned once, by --assign-ids, and written into the staging file; a row
that already has one is never touched, so a later title correction cannot move
it. The slug is the lower-cased work title folded to ASCII, runs of anything
else become one hyphen, and it is cut at a hyphen boundary to 60 characters.
Two rows of one volume with the same slug take `-2`, `-3` in staging order.
A row lands in every bucket its `atlas_ids` name, so one `row_id` may appear in
several buckets; corpus_map.validate() requires that it always be the same work.
"""
from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
MAP_DIR = REPO_ROOT / "cic" / "corpus-map"
STAGING = MAP_DIR / "_staging"

sys.path.insert(0, str(HERE))

# Files under cic/corpus-map/ that are not buckets and must never be merged
# into or overwritten.
_NOT_A_BUCKET = {"ATLAS-TARGETS.md", "README.md", "_staging"}

_KEEP = ("row_id", "work", "author", "source_file", "locus", "role", "confidence", "note")

_GENERATED = (
    "# GENERATED by cic/engine/corpus_map_merge.py from cic/corpus-map/_staging/.\n"
    "# Edit the staging file for the source volume, not this file - a re-merge\n"
    "# overwrites it. The filename is the census movement id; that is the join.\n")
_GENERATED_FIRST_LINE = _GENERATED.split("\n")[0]

# Ruling kinds for an author CCEL's metadata does not supply. The brief (§7)
# separates them because they need different answers, and collapsing them is
# how "the Didache" ends up filed under a person who does not exist.
RULING_KINDS = {
    "metadata-omission",   # anf01 names only `irenaeus`; its sections carry seven more
    "anonymous",           # the Didache, the conciliar acts - a work, not a person
    "pseudonymous",        # the Pastor of Hermas, the Clementina
}


ONLY: list[str] = []          # set by --only; empty means every staging file


def load_staging() -> tuple[list[dict], dict[str, dict], list[str]]:
    """Every staged assignment, flattened, plus the author rulings, plus
    findings. The file each row came from is attached so a finding can name it.

    Author rulings ride in the staging files rather than in one shared file for
    the same reason assignments do: a worker owns its own file and nothing
    else, so nothing can race. The merge collects them."""
    import yaml

    rows: list[dict] = []
    rulings: dict[str, dict] = {}
    findings: list[str] = []
    seen_ids: dict[str, str] = {}
    if not STAGING.is_dir():
        return rows, rulings, [f"no staging directory at {STAGING.relative_to(REPO_ROOT)}"]

    for path in sorted(STAGING.glob("*.yaml")):
        if ONLY and not any(token in path.name for token in ONLY):
            continue
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        source_file = doc.get("source_file")
        if not source_file:
            findings.append(f"{path.name}: no `source_file`")
            continue
        entries = doc.get("assignments")
        if not isinstance(entries, list):
            findings.append(f"{path.name}: `assignments` is not a list")
            continue
        for slug, ruling in (doc.get("authors_ruled") or {}).items():
            if not isinstance(ruling, dict):
                findings.append(f"{path.name}: authors_ruled[{slug!r}] is not a mapping")
                continue
            if ruling.get("kind") not in RULING_KINDS:
                findings.append(f"{path.name}: authors_ruled[{slug!r}] kind "
                                f"{ruling.get('kind')!r} not in {sorted(RULING_KINDS)}")
            if not str(ruling.get("evidence") or "").strip():
                findings.append(f"{path.name}: authors_ruled[{slug!r}] has no `evidence` - "
                                "a ruling with no stated basis is a guess (§6.2)")
            rulings.setdefault(slug, {**ruling, "from_file": source_file})

        for i, entry in enumerate(entries):
            if not isinstance(entry, dict):
                findings.append(f"{path.name}[{i}]: not a mapping")
                continue
            ids = entry.get("atlas_ids")
            if isinstance(ids, str):
                ids = [ids]
            if not ids:
                findings.append(f"{path.name}[{i}] {entry.get('work')!r}: no `atlas_ids` - "
                                "a work with nowhere to go should be listed with "
                                "`confidence: needs-ruling` against its best guess, not dropped")
                continue
            row_id = entry.get("row_id")
            if row_id is not None:
                if not isinstance(row_id, str) or not row_id.strip():
                    findings.append(f"{path.name}[{i}] {entry.get('work')!r}: `row_id` is not a non-empty string")
                elif row_id in seen_ids:
                    findings.append(f"{path.name}[{i}] {entry.get('work')!r}: `row_id` {row_id!r} "
                                    f"already used by {seen_ids[row_id]}")
                else:
                    seen_ids[row_id] = f"{path.name}[{i}]"
            row = {k: entry[k] for k in _KEEP if entry.get(k) is not None}
            row.setdefault("source_file", source_file)
            rows.append({**row, "_atlas_ids": list(ids), "_from": path.name})
    return rows, rulings, findings


_SLUG_MAX = 60


def work_slug(work: object) -> str:
    """The deterministic slug half of a row_id."""
    folded = unicodedata.normalize("NFKD", str(work or "")).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "-", folded.lower()).strip("-")
    if len(slug) > _SLUG_MAX:
        cut = slug[:_SLUG_MAX]
        slug = cut.rsplit("-", 1)[0] if "-" in cut and slug[_SLUG_MAX] != "-" else cut
        slug = slug.strip("-")
    return slug or "work"


def assign_ids(write: bool = True) -> tuple[int, int, list[str]]:
    """Give every staging row lacking a `row_id` one. Returns (assigned,
    collisions resolved, findings). A row that has an id is never changed.
    The id is inserted as the row's first key by editing the file's text, so
    comments and layout in the staging file survive."""
    import yaml

    findings: list[str] = []
    files: list[tuple[Path, str, list[tuple[int, int]]]] = []
    used: set[str] = set()
    for path in sorted(STAGING.glob("*.yaml")):
        text = path.read_text(encoding="utf-8")
        node = yaml.compose(text)
        seq = next((v for k, v in node.value if k.value == "assignments"), None) if node else None
        if not isinstance(seq, yaml.SequenceNode):
            findings.append(f"{path.name}: `assignments` is not a list")
            continue
        entries = []
        for item in seq.value:
            if not isinstance(item, yaml.MappingNode) or item.flow_style:
                findings.append(f"{path.name}: line {item.start_mark.line + 1}: row is not a block mapping")
                continue
            entries.append((item.start_mark.line, item.start_mark.column))
        files.append((path, text, entries))
        doc = yaml.safe_load(text) or {}
        for entry in doc.get("assignments") or []:
            if isinstance(entry, dict) and isinstance(entry.get("row_id"), str):
                used.add(entry["row_id"])

    assigned = collisions = 0
    for path, text, entries in files:
        doc = yaml.safe_load(text) or {}
        rows = doc.get("assignments") or []
        lines = text.split("\n")
        inserts: list[tuple[int, str]] = []
        for (line_no, col), row in zip(entries, rows):
            if row.get("row_id") is not None:
                continue
            base = f"{path.stem}--{work_slug(row.get('work'))}"
            row_id, n = base, 1
            while row_id in used:
                n += 1
                row_id = f"{base}-{n}"
            collisions += n > 1
            used.add(row_id)
            if lines[line_no][col - 2:col] != "- ":
                findings.append(f"{path.name}: line {line_no + 1}: cannot place row_id")
                continue
            inserts.append((line_no, f"{lines[line_no][:col - 2]}- row_id: {row_id}\n"
                                      f"{' ' * col}{lines[line_no][col:]}"))
            assigned += 1
        if inserts and write:
            for line_no, replacement in inserts:
                lines[line_no] = replacement
            path.write_text("\n".join(lines), encoding="utf-8")
    return assigned, collisions, findings


def merge(write: bool = True, write_only: list[str] | None = None) -> tuple[dict[str, list[dict]], list[str]]:
    """write_only, distinct from the module-level ONLY (--check's own
    filter): ONLY restricts what gets READ, which is right for one worker
    validating its own file in isolation but wrong for a real write (a
    partial read makes every bucket outside it look orphaned - the reason
    main() below still refuses to combine ONLY with a real merge).
    write_only restricts only what gets WRITTEN: it still reads every
    staging file, so a bucket two volumes both touch is computed from
    both, correctly - it just skips writing any bucket that the matching
    staging file(s) don't themselves reference, and skips pruning
    entirely, because a scoped run only ever has a partial view of which
    buckets are truly orphaned. This exists for exactly the case a
    single build thread's own intake work needs: land its own world's
    assignment without touching (or risking pruning) another world's
    still-in-progress staging file, mid-flight in a different thread at
    the same time. Run a full, unscoped merge periodically - or whenever
    a deliberate, authoritative pass is actually wanted - to pick up
    anything a run of scoped merges left unpruned."""
    import yaml

    rows, rulings, findings = load_staging()
    buckets: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        payload = {k: v for k, v in row.items() if not k.startswith("_")}
        for atlas_id in row["_atlas_ids"]:
            buckets[atlas_id].append(payload)

    # A work twice in ONE bucket is a duplicate - two workers reading the same
    # work out of two volumes, or one worker listing it twice. The same work in
    # several buckets is expected and is NOT touched.
    for atlas_id, works in buckets.items():
        seen: dict[tuple, str] = {}
        for w in works:
            key = (str(w.get("work", "")).strip().lower(), str(w.get("source_file", "")))
            if key in seen:
                findings.append(f"{atlas_id}: {w.get('work')!r} assigned twice from the same file")
            seen[key] = atlas_id

    for atlas_id in buckets:
        buckets[atlas_id].sort(key=lambda w: (str(w.get("author", "")), str(w.get("work", ""))))

    if write and rulings:
        header = ("# GENERATED by cic/engine/corpus_map_merge.py from the `authors_ruled`\n"
                  "# blocks of cic/corpus-map/_staging/*.yaml. Every entry is an author or\n"
                  "# work-entity CCEL's own metadata does not supply, with the evidence for\n"
                  "# the ruling. corpus_map.py accepts these as valid `author` values.\n")
        (MAP_DIR / "UNATTRIBUTED.yaml").write_text(
            header + yaml.safe_dump({"authors": dict(sorted(rulings.items()))},
                                    sort_keys=False, allow_unicode=True, width=88),
            encoding="utf-8")

    if write:
        if write_only:
            in_scope = {
                atlas_id
                for row in rows
                if any(token in row["_from"] for token in write_only)
                for atlas_id in row["_atlas_ids"]
            }
            target_ids = sorted(in_scope & buckets.keys())
        else:
            target_ids = sorted(buckets.keys())

        for atlas_id in target_ids:
            works = buckets[atlas_id]
            if atlas_id in _NOT_A_BUCKET:
                findings.append(f"refusing to write bucket named {atlas_id!r}")
                continue
            doc = {"atlas_id": atlas_id, "works": works}
            (MAP_DIR / f"{atlas_id}.yaml").write_text(
                _GENERATED + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=88),
                encoding="utf-8")

        # Prune buckets the staging no longer produces. Without this a work
        # moved from one entry to another leaves the old bucket standing, and
        # a generated directory that keeps its own history is not generated.
        # Only files carrying the header are ever removed: anything a human
        # wrote by hand is left alone and reported instead.
        #
        # SKIPPED ENTIRELY when write_only is set: pruning decides a bucket
        # is orphaned because NO staging produces it - a decision that needs
        # the full picture this run's restricted WRITE deliberately doesn't
        # act on. A scoped run leaving a truly-orphaned bucket standing a
        # while longer is the safe failure; a scoped run deleting a bucket
        # another thread's staging file was mid-write on is not.
        if not write_only:
            for path in MAP_DIR.glob("*.yaml"):
                # UNATTRIBUTED.yaml, WORKS.yaml (works_registry.py) and
                # AUTHOR-IDS.yaml (author_ids.py) are all hand-written registries
                # that live beside the buckets, not buckets themselves - the same
                # fact corpus_map.py's own NON_BUCKET_FILES tracks for its
                # loader. Two separate lists in two scripts rather than one
                # shared constant (pre-existing shape, not changed here) - keep
                # them in sync by hand when either grows.
                if path.stem in buckets or path.name in _NOT_A_BUCKET | {
                        "UNATTRIBUTED.yaml", "WORKS.yaml", "AUTHOR-IDS.yaml", "PAIRS.yaml"}:
                    continue
                if path.read_text(encoding="utf-8").startswith(_GENERATED_FIRST_LINE):
                    path.unlink()
                else:
                    findings.append(f"{path.name}: hand-written, and nothing in staging produces it "
                                    "any more - merge left it alone; move it into _staging/ or delete it")
    return buckets, findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python cic/engine/corpus_map_merge.py")
    parser.add_argument("--check", action="store_true", help="report only; write nothing")
    parser.add_argument("--assign-ids", action="store_true",
                        help="give every staging row without a `row_id` one, written into its "
                             "staging file; never changes an existing id. With --check: report "
                             "how many would be assigned, write nothing. Run a full merge after.")
    parser.add_argument("--only", nargs="*", default=[], metavar="TOKEN",
                        help="with --check: consider only staging files whose name contains one "
                             "of these, so a worker can validate its own files while others are "
                             "mid-write")
    parser.add_argument("--write-only", nargs="*", default=None, metavar="TOKEN",
                        help="write only the Atlas-entry bucket(s) that staging file(s) whose "
                             "name contains one of these tokens actually touch - still reads "
                             "every staging file for a correct picture of those buckets' full "
                             "contents, just restricts what lands on disk, and skips pruning "
                             "entirely (see merge()'s own docstring for why). Use this from "
                             "inside one build thread's own intake work so it can never touch or "
                             "prune another world's still-in-progress staging file; run a plain, "
                             "full merge (no flags) periodically for the complete, authoritative "
                             "pass.")
    args = parser.parse_args(argv)
    if args.only and not args.check:
        parser.error("--only is for --check; a partial merge would prune every other bucket")
    if args.write_only is not None and args.check:
        parser.error("--write-only writes buckets; --check writes nothing. Use one or the other.")
    if args.write_only == []:
        parser.error("--write-only needs at least one token - an empty list would write nothing")
    ONLY[:] = args.only
    if args.assign_ids:
        if args.only or args.write_only is not None:
            parser.error("--assign-ids covers every staging file; do not combine it with --only or --write-only")
        assigned, collisions, findings = assign_ids(write=not args.check)
        verb = "would assign" if args.check else "assigned"
        print(f"{verb} {assigned} row_id(s); {collisions} slug collision(s) resolved")
        for f in findings:
            print(f"  {f}")
        return 1 if findings else 0

    buckets, findings = merge(write=not args.check, write_only=args.write_only)
    _, rulings, _ = load_staging()
    total = sum(len(v) for v in buckets.values())
    staged = len({(w.get("work"), w.get("source_file")) for ws in buckets.values() for w in ws})
    scope_note = ""
    if args.check:
        scope_note = "  [check only, nothing written]"
    elif args.write_only:
        scope_note = f"  [scoped write: {' '.join(args.write_only)!r} - pruning skipped]"
    print(f"{staged} distinct work(s) → {total} assignment(s) across {len(buckets)} Atlas entry(ies)"
          + scope_note)

    multi = sorted(((len({a for a, ws in buckets.items() if any(
        w.get("work") == work and w.get("source_file") == src for w in ws)}), work)
        for work, src in {(w.get("work"), w.get("source_file")) for ws in buckets.values() for w in ws}),
        reverse=True)
    shared = [(n, w) for n, w in multi if n > 1]
    print(f"  {len(shared)} work(s) assigned to more than one entry (expected - assignment is not exclusive)")
    for n, work in shared[:8]:
        print(f"    {n}x  {work}")

    if rulings:
        kinds: dict[str, int] = {}
        for r in rulings.values():
            kinds[r.get("kind", "?")] = kinds.get(r.get("kind", "?"), 0) + 1
        print(f"  {len(rulings)} author ruling(s) for material CCEL does not attribute: {kinds}")

    if findings:
        print(f"\n{len(findings)} staging finding(s):")
        for f in findings:
            print(f"  {f}")

    if not args.check and buckets:
        print()
        from corpus_map import report
        return report()
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
