#!/usr/bin/env python3
"""Merge per-volume assignment staging files into the corpus map.

WHY A STAGING STEP AT ALL. The map is stored one file per Atlas entry, which
is right for reading and for the `census_id -> filename` join. It is exactly
wrong for writing: the assignment work partitions naturally by SOURCE VOLUME
(one worker reads anf02, another npnf204), and any two volumes can contribute
to the same Atlas entry - Athanasius' Vita in npnf204 and Palladius' Lausiac
History both land in `desert-monasticism`. Parallel workers writing bucket
files directly would race on exactly the entries that matter most, and the
loser's work would vanish silently.

So workers write `cic/corpus-map/_staging/<volume>.yaml`, one file each, never
shared. Each entry is ONE WORK with the atlas entries it belongs to:

    source_file: anf02_hermas-tatian-athenagoras-theophilus-clement-alexandria.xml
    assignments:
      - work: "The Stromata"
        author: clement_alex
        locus: "div2 5.4"
        atlas_ids: [alexandria-catechetical]
        role: tradition
        confidence: assigned
        note: >
          ...

This transposes that to the stored shape. The two are the same data: per-work
with many entries, and per-entry with many works, are projections of one
relation. The staging shape is the writer's view; the bucket shape is the
reader's.

NON-EXCLUSIVITY SURVIVES THE MERGE, and that is the point of doing it here
rather than by hand. A work naming three `atlas_ids` is written into three
bucket files, deliberately: an exclusive partition would strip desert of the
Vita Antonii, which is its evidential base. See corpus_map.py's docstring.

    python cic/engine/corpus_map_merge.py --check    # report, write nothing
    python cic/engine/corpus_map_merge.py            # merge, then validate
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
MAP_DIR = REPO_ROOT / "cic" / "corpus-map"
STAGING = MAP_DIR / "_staging"

sys.path.insert(0, str(HERE))

# Files under cic/corpus-map/ that are not buckets and must never be merged
# into or overwritten.
_NOT_A_BUCKET = {"ATLAS-TARGETS.md", "README.md", "_staging"}

_KEEP = ("work", "author", "source_file", "locus", "role", "confidence", "note")

_GENERATED = (
    "# GENERATED by cic/engine/corpus_map_merge.py from cic/corpus-map/_staging/.\n"
    "# Edit the staging file for the source volume, not this file - a re-merge\n"
    "# overwrites it. The filename is the census movement id; that is the join.\n")
_GENERATED_FIRST_LINE = _GENERATED.split("\n")[0]

# Ruling kinds for an author CCEL's metadata does not supply. The brief (§7)
# separates them because they need different answers, and collapsing them is
# how "the Didache" ends up filed under a person who does not exist.
RULING_KINDS = {
    "metadata-omission",   # anf01 names only `irenaeus`; its sections carry seven more
    "anonymous",           # the Didache, the conciliar acts - a work, not a person
    "pseudonymous",        # the Pastor of Hermas, the Clementina
}


def load_staging() -> tuple[list[dict], dict[str, dict], list[str]]:
    """Every staged assignment, flattened, plus the author rulings, plus
    findings. The file each row came from is attached so a finding can name it.

    Author rulings ride in the staging files rather than in one shared file for
    the same reason assignments do: a worker owns its own file and nothing
    else, so nothing can race. The merge collects them."""
    import yaml

    rows: list[dict] = []
    rulings: dict[str, dict] = {}
    findings: list[str] = []
    if not STAGING.is_dir():
        return rows, rulings, [f"no staging directory at {STAGING.relative_to(REPO_ROOT)}"]

    for path in sorted(STAGING.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        source_file = doc.get("source_file")
        if not source_file:
            findings.append(f"{path.name}: no `source_file`")
            continue
        entries = doc.get("assignments")
        if not isinstance(entries, list):
            findings.append(f"{path.name}: `assignments` is not a list")
            continue
        for slug, ruling in (doc.get("authors_ruled") or {}).items():
            if not isinstance(ruling, dict):
                findings.append(f"{path.name}: authors_ruled[{slug!r}] is not a mapping")
                continue
            if ruling.get("kind") not in RULING_KINDS:
                findings.append(f"{path.name}: authors_ruled[{slug!r}] kind "
                                f"{ruling.get('kind')!r} not in {sorted(RULING_KINDS)}")
            if not str(ruling.get("evidence") or "").strip():
                findings.append(f"{path.name}: authors_ruled[{slug!r}] has no `evidence` - "
                                "a ruling with no stated basis is a guess (§6.2)")
            rulings.setdefault(slug, {**ruling, "from_file": source_file})

        for i, entry in enumerate(entries):
            if not isinstance(entry, dict):
                findings.append(f"{path.name}[{i}]: not a mapping")
                continue
            ids = entry.get("atlas_ids")
            if isinstance(ids, str):
                ids = [ids]
            if not ids:
                findings.append(f"{path.name}[{i}] {entry.get('work')!r}: no `atlas_ids` - "
                                "a work with nowhere to go should be listed with "
                                "`confidence: needs-ruling` against its best guess, not dropped")
                continue
            row = {k: entry[k] for k in _KEEP if entry.get(k) is not None}
            row.setdefault("source_file", source_file)
            rows.append({**row, "_atlas_ids": list(ids), "_from": path.name})
    return rows, rulings, findings


def merge(write: bool = True) -> tuple[dict[str, list[dict]], list[str]]:
    import yaml

    rows, rulings, findings = load_staging()
    buckets: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        payload = {k: v for k, v in row.items() if not k.startswith("_")}
        for atlas_id in row["_atlas_ids"]:
            buckets[atlas_id].append(payload)

    # A work twice in ONE bucket is a duplicate - two workers reading the same
    # work out of two volumes, or one worker listing it twice. The same work in
    # several buckets is expected and is NOT touched.
    for atlas_id, works in buckets.items():
        seen: dict[tuple, str] = {}
        for w in works:
            key = (str(w.get("work", "")).strip().lower(), str(w.get("source_file", "")))
            if key in seen:
                findings.append(f"{atlas_id}: {w.get('work')!r} assigned twice from the same file")
            seen[key] = atlas_id

    for atlas_id in buckets:
        buckets[atlas_id].sort(key=lambda w: (str(w.get("author", "")), str(w.get("work", ""))))

    if write and rulings:
        header = ("# GENERATED by cic/engine/corpus_map_merge.py from the `authors_ruled`\n"
                  "# blocks of cic/corpus-map/_staging/*.yaml. Every entry is an author or\n"
                  "# work-entity CCEL's own metadata does not supply, with the evidence for\n"
                  "# the ruling. corpus_map.py accepts these as valid `author` values.\n")
        (MAP_DIR / "UNATTRIBUTED.yaml").write_text(
            header + yaml.safe_dump({"authors": dict(sorted(rulings.items()))},
                                    sort_keys=False, allow_unicode=True, width=88),
            encoding="utf-8")

    if write:
        for atlas_id, works in sorted(buckets.items()):
            if atlas_id in _NOT_A_BUCKET:
                findings.append(f"refusing to write bucket named {atlas_id!r}")
                continue
            doc = {"atlas_id": atlas_id, "works": works}
            (MAP_DIR / f"{atlas_id}.yaml").write_text(
                _GENERATED + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=88),
                encoding="utf-8")

        # Prune buckets the staging no longer produces. Without this a work
        # moved from one entry to another leaves the old bucket standing, and
        # a generated directory that keeps its own history is not generated.
        # Only files carrying the header are ever removed: anything a human
        # wrote by hand is left alone and reported instead.
        for path in MAP_DIR.glob("*.yaml"):
            if path.stem in buckets or path.name in _NOT_A_BUCKET | {"UNATTRIBUTED.yaml"}:
                continue
            if path.read_text(encoding="utf-8").startswith(_GENERATED_FIRST_LINE):
                path.unlink()
            else:
                findings.append(f"{path.name}: hand-written, and nothing in staging produces it "
                                "any more - merge left it alone; move it into _staging/ or delete it")
    return buckets, findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python cic/engine/corpus_map_merge.py")
    parser.add_argument("--check", action="store_true", help="report only; write nothing")
    args = parser.parse_args(argv)

    buckets, findings = merge(write=not args.check)
    _, rulings, _ = load_staging()
    total = sum(len(v) for v in buckets.values())
    staged = len({(w.get("work"), w.get("source_file")) for ws in buckets.values() for w in ws})
    print(f"{staged} distinct work(s) → {total} assignment(s) across {len(buckets)} Atlas entry(ies)"
          + ("  [check only, nothing written]" if args.check else ""))

    multi = sorted(((len({a for a, ws in buckets.items() if any(
        w.get("work") == work and w.get("source_file") == src for w in ws)}), work)
        for work, src in {(w.get("work"), w.get("source_file")) for ws in buckets.values() for w in ws}),
        reverse=True)
    shared = [(n, w) for n, w in multi if n > 1]
    print(f"  {len(shared)} work(s) assigned to more than one entry (expected - assignment is not exclusive)")
    for n, work in shared[:8]:
        print(f"    {n}x  {work}")

    if rulings:
        kinds: dict[str, int] = {}
        for r in rulings.values():
            kinds[r.get("kind", "?")] = kinds.get(r.get("kind", "?"), 0) + 1
        print(f"  {len(rulings)} author ruling(s) for material CCEL does not attribute: {kinds}")

    if findings:
        print(f"\n{len(findings)} staging finding(s):")
        for f in findings:
            print(f"  {f}")

    if not args.check and buckets:
        print()
        from corpus_map import report
        return report()
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
