"""The world table - the ONLY per-world configuration in the clean engine.

One row per world: identity, record-store directory, core record ids, and
the rebuilt flag (readability enforcement). Everything else per-world is a
RECORD (craft table included). A world is added to the clean system by
adding its row here and its records under cic/records/<key>/ - no new code.
"""

WORLDS = {
    "desert": {
        "world_id": "desert-monasticism",
        "records_dir": "desert",
        "world_core_id": "desertcore001",
        "voice_profile_id": "desertvoice001",
        "craft_id": "desertcraft001",
        "prompt_filename": "desert_Representative_Permanent_Prompt_Papnoute.txt",
        "capsule_filename": "desert_World_Capsule_Core.md",
        "capsule_display_name": "Desert Monasticism",
        "world_code": "desert",
        "chunk_style": "desert",
        "capsule_style": "desert",
        "rebuilt": False,
    },
    "hieronymian": {
        "world_id": "hieronymian-ascetic-literary",
        "records_dir": "hieronymian",
        "world_core_id": "halcore001",
        "voice_profile_id": "halvoice001",
        "craft_id": "halcraft001",
        "prompt_filename": "hal_Representative_Permanent_Prompt_Albina.txt",
        "capsule_filename": "hal_World_Capsule_Core.md",
        "capsule_display_name": "Hieronymian",
        "world_code": "hal",
        "chunk_style": "hal",
        "rebuilt": True,
    },
    "imperial_juridical": {
        "world_id": "imperial-juridical-christianity",
        "records_dir": "imperial_juridical",
        "world_core_id": "ijccore001",
        "voice_profile_id": "ijcvoice001",
        "craft_id": "ijccraft001",
        "prompt_filename": "ijc_Representative_Permanent_Prompt_Marius.txt",
        "capsule_filename": "ijc_World_Capsule_Core.md",
        "capsule_display_name": "Imperial-Juridical",
        "world_code": "ijc",
        "chunk_style": "ijc",
        "capsule_story_style": "title-only",
        "rebuilt": True,
    },
    "pahc": {
        "world_id": "post-apostolic-house-church",
        "records_dir": "pahc",
        "world_core_id": "pahccore001",
        "voice_profile_id": "pahcvoice001",
        "craft_id": "pahccraft001",
        "prompt_filename": "pahc_Representative_Permanent_Prompt_Chloe.txt",
        "capsule_filename": "pahc_World_Capsule_Core.md",
        "capsule_display_name": "Post-Apostolic House-Church",
        "world_code": "pahc",
        "chunk_style": "pahc",
        "rebuilt": True,
    },
    "alexandria": {
        "world_id": "alexandria-catechetical",
        "records_dir": "alexandria",
        "world_core_id": "alexcore001",
        "voice_profile_id": "alexvoice001",
        "craft_id": "alxcraft001",
        "prompt_filename": "alex_Representative_Permanent_Prompt_Theon.txt",
        "capsule_filename": "alex_World_Capsule_Core.md",
        "capsule_display_name": "Alexandria",
        "world_code": "alex",
        "chunk_style": "alx",
        "capsule_terms": {"tiers": [1], "require_world_meaning": True, "cap": 12},
        "rebuilt": True,
    },
    "syriac": {
        "world_id": "syriac-edessa-nisibis",
        "records_dir": "syriac",
        "world_core_id": "syrcore001",
        "voice_profile_id": "syrvoice001",
        "craft_id": "syrcraft001",
        "prompt_filename": "syr_Representative_Permanent_Prompt_Yausep.txt",
        "capsule_filename": "syr_World_Capsule_Core.md",
        "capsule_display_name": "Syriac",
        "world_code": "syr",
        "chunk_style": "syr",
        "capsule_terms": {"tiers": [1, 2], "require_world_meaning": False, "cap": None},
        "rebuilt": True,
    },
}
