"""Blind pairing of two Doc_10 drafts: a seed assigns labels A and B, header
identity fields are scrubbed, and a checksummed mapping file keeps the key."""
from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path

from .common import REPO_ROOT, Finding, rel, world_dir

DRAFTERS = ("sonnet", "fable")
WITHHELD = "[withheld]"

NAME = re.compile(r"\b(?:Sonnet|Fable|Opus|Claude|Haiku)\b|claude-[\w.\-]+", re.IGNORECASE)
MODEL_ID = re.compile(r"claude-[\w.\-]+", re.IGNORECASE)
FIELD = re.compile(
    r"^(?P<head>\s*(?:[-*>|]\s*)*\**\s*(?:drafter|drafted by|model|effort|author|written by|generated by)\b\**\s*[:|]?\**\s*)(?P<value>.*)$",
    re.IGNORECASE,
)
FRONT_MATTER_FENCE = re.compile(r"^---\s*$")
SECOND_LEVEL_HEADING = re.compile(r"^##\s")


@dataclass
class Scrubbed:
    text: str
    report: list[dict]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def assign_labels(seed: str) -> dict[str, str]:
    """Label to drafter, decided only by the seed."""
    first = hashlib.sha256(seed.encode("utf-8")).digest()[0] & 1
    order = DRAFTERS if first == 0 else DRAFTERS[::-1]
    return {"A": order[0], "B": order[1]}


def header_end(lines: list[str]) -> int:
    """Index of the first body line. The header is the front matter, if any,
    plus everything before the first second-level heading."""
    end = 0
    if lines and FRONT_MATTER_FENCE.match(lines[0]):
        for i in range(1, len(lines)):
            if FRONT_MATTER_FENCE.match(lines[i]):
                end = i + 1
                break
    for i, line in enumerate(lines):
        if SECOND_LEVEL_HEADING.match(line):
            return max(end, i)
    return end


def scrub_draft(text: str) -> Scrubbed:
    """Scrub identity from header fields only. Every other name occurrence is
    reported, header or body, and left as written."""
    lines = text.splitlines(keepends=True)
    end = header_end(lines)
    report: list[dict] = []
    out: list[str] = []
    for number, line in enumerate(lines, start=1):
        body = line.rstrip("\r\n")
        ending = line[len(body):]
        if number <= end:
            field = FIELD.match(body)
            if field:
                if field.group("value").strip():
                    report.append({"kind": "field-scrubbed", "region": "header", "line": number, "original": body})
                    out.append(field.group("head") + WITHHELD + ending)
                else:
                    out.append(line)
                continue
            if MODEL_ID.search(body) and re.match(r"^\s*(?:[-*>|]\s*)*[\w \-]+\s*:", body):
                scrubbed = MODEL_ID.sub(WITHHELD, body)
                report.append({"kind": "field-scrubbed", "region": "header", "line": number, "original": body})
                out.append(scrubbed + ending)
                continue
        for m in NAME.finditer(body):
            report.append({
                "kind": "mention",
                "region": "header" if number <= end else "body",
                "line": number,
                "text": m.group(0),
            })
        out.append(line)
    return Scrubbed("".join(out), report)


def mentions(report: list[dict]) -> list[dict]:
    return [r for r in report if r["kind"] == "mention"]


def _read(path: Path, findings: list[Finding], name: str) -> str | None:
    if not path.is_file():
        findings.append(Finding(str(path), "blind-input", f"the {name} draft does not exist"))
        return None
    try:
        return path.read_bytes().decode("utf-8")
    except UnicodeDecodeError:
        findings.append(Finding(str(path), "blind-input", f"the {name} draft is not valid UTF-8"))
        return None


def _resolve(raw: Path) -> Path:
    return raw if raw.is_absolute() else Path.cwd() / raw


def mapping_path(code: str, out_dir: Path) -> Path:
    return out_dir / f"{code}_Doc10_Blind_Mapping.json"


def blind(
    code: str,
    sonnet: Path,
    fable: Path,
    *,
    seed: str | None = None,
    out_dir: Path | None = None,
    root: Path = REPO_ROOT,
    allow_body_mentions: bool = False,
    force: bool = False,
) -> tuple[list[Finding], dict | None, str | None]:
    """Returns findings, the mapping written (None on failure), and its sha256."""
    findings: list[Finding] = []
    out_dir = _resolve(out_dir) if out_dir else world_dir(code, root) / "build"
    sources = {"sonnet": _resolve(sonnet), "fable": _resolve(fable)}
    if sources["sonnet"].resolve() == sources["fable"].resolve():
        findings.append(Finding(str(sources["sonnet"]), "blind-input", "the sonnet and fable drafts are the same file"))
    texts = {name: _read(path, findings, name) for name, path in sources.items()}
    if findings:
        return findings, None, None

    scrubbed = {name: scrub_draft(text) for name, text in texts.items()}
    found = {name: mentions(s.report) for name, s in scrubbed.items()}
    if not allow_body_mentions:
        for name, items in found.items():
            for item in items:
                findings.append(Finding(
                    f"{sources[name]}:{item['line']}",
                    "blind-body-mention",
                    f"{item['region']} names {item['text']!r}; blinding never edits prose; edit the source draft or pass --allow-body-mentions",
                ))
        if findings:
            return findings, None, None

    seed = seed if seed is not None else os.urandom(16).hex()
    labels = assign_labels(seed)
    targets = {label: out_dir / f"Doc_10_{label}.md" for label in labels}
    map_file = mapping_path(code, out_dir)
    if not force:
        for path in (*targets.values(), map_file):
            if path.exists():
                findings.append(Finding(rel(path, root), "blind-overwrite", "already exists; pass --force to replace it"))
        if findings:
            return findings, None, None

    out_dir.mkdir(parents=True, exist_ok=True)
    scrubbed_info: dict[str, dict] = {}
    report: list[dict] = []
    for label, drafter in labels.items():
        data = scrubbed[drafter].text.encode("utf-8")
        targets[label].write_bytes(data)
        scrubbed_info[label] = {"path": rel(targets[label], root), "sha256": sha256_bytes(data)}
        report.extend({"draft": label, **entry} for entry in scrubbed[drafter].report)
    mapping = {
        "world": code,
        "seed": seed,
        "labels": labels,
        "originals": {
            name: {"path": rel(sources[name], root), "sha256": sha256_bytes(texts[name].encode("utf-8"))}
            for name in DRAFTERS
        },
        "scrubbed": scrubbed_info,
        "scrub_report": report,
    }
    map_file.write_text(json.dumps(mapping, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return [], mapping, sha256_file(map_file)


def reveal(mapping_file: Path, checksum: str, root: Path = REPO_ROOT) -> tuple[list[Finding], dict | None]:
    mapping_file = _resolve(mapping_file)
    where = rel(mapping_file, root)
    if not mapping_file.is_file():
        return [Finding(where, "reveal-mapping", "the mapping file does not exist")], None
    actual = sha256_file(mapping_file)
    if actual != checksum.strip().lower():
        return [Finding(where, "reveal-checksum", f"sha256 is {actual}, not the recorded {checksum.strip().lower()}; the mapping file changed or the wrong checksum was given; nothing revealed")], None
    try:
        mapping = json.loads(mapping_file.read_text(encoding="utf-8"))
        labels, scrubbed = mapping["labels"], mapping["scrubbed"]
    except (ValueError, KeyError):
        return [Finding(where, "reveal-mapping", "the mapping file is not a valid blind mapping")], None
    findings: list[Finding] = []
    for label, info in sorted(scrubbed.items()):
        path = root / info["path"]
        if not path.is_file():
            findings.append(Finding(info["path"], "reveal-draft", f"draft {label} is missing from disk"))
        elif sha256_file(path) != info["sha256"]:
            findings.append(Finding(info["path"], "reveal-draft", f"draft {label} changed after blinding; its sha256 no longer matches the mapping"))
    return findings, mapping
